### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by chriskrycho** [ember-codemods/ember-component-template-colocation-migrator#10]
I'd love to be able to [`volta install`](https://docs.volta.sh/guide/understanding#installing-package-binaries) this for recurrent local use (rather than using `npx`); could you publish it to npm to support that use case?

**Comment by rwjblue** [comment]
Ya, I'll get this workin'....

**Comment by chriskrycho** [comment]
Friendly ping!

**Comment by rwjblue** [comment]
Yikes!

**Comment by rwjblue** [comment]
https://www.npmjs.com/package/ember-component-template-colocation-migrator
