### ISSUE TITLE
Move ownership to github.com/ember-codemods

### ISSUE THREAD

**Issue by GavinJoyce** [ember-codemods/ember-component-template-colocation-migrator#3]

**Comment by rwjblue** [comment]
@GavinJoyce - I've invited you to the ember-codemods org (so you can move this into there), if you go to https://github.com/ember-codemods you should be able to accept (and then you can move the repo).

**Comment by GavinJoyce** [comment]
Thanks, it's been moved to https://github.com/ember-codemods/ember-component-template-colocation-migrator
