### ISSUE TITLE
Support `--component-structure=nested`?

### ISSUE THREAD

**Issue by chancancode** [ember-codemods/ember-component-template-colocation-migrator#5]
The [RFC](https://emberjs.github.io/rfcs/0481-component-templates-co-location.html#generator) supports a "nested" mode (`app/components/foo-bar/index.{js,hbs}`). We should probably allow that here as well. Import paths may need to be updated as well. Outside thing can and should import them without the `/index` in the path, but if the file does any relative imports there will be an extra level of `../` in this case.

**Comment by ijlee2** [comment]
Hello. For work, I'd like to modify your script to convert `classic` component structure to `nested`, then make a PR if successful (I have a timebox) and let you make improvements as needed.

It seems that, for `classic` to `flat`, you had to check for (perhaps, less commonly used) things like layouts and partials. I'm not too familiar with these so I'd need to read up on them.

Are there pitfalls like these that I need to be aware of? I was hoping the conversion would be as easy as moving files from `app/components/foo-bar.js` and `app/templates/components/foo-bar.hbs` to `app/components/foo-bar/index.{hbs,js}`. (Similarly, moving nested files isn't a problem.)

Can you further describe to me what is meant by the need to update import paths in the comment above? I didn't quite understand the potential problem.

Thanks,

**Comment by rwjblue** [comment]
This was resolved in #11
