### ISSUE TITLE
Work with Addons?

### ISSUE THREAD

**Issue by scottkidder** [ember-codemods/ember-component-template-colocation-migrator#7]
I'd like to run this codemod on an addon. When I tried, it deletes all the template re-export javascript files e.g. `app/templates/components/my-component.js` and does nothing else.

**Comment by rwjblue** [comment]
I was just chatting with @chriskrycho about this earlier today. Definitely would like to get support landed (would really help with in-repo addons for example).

**Comment by chriskrycho** [comment]
I'm actively exploring it, will *hopefully* have something in a day or two!

**Comment by chriskrycho** [comment]
Not a day or two, as other things came up, but still *soon* I hope!

**Comment by rwjblue** [comment]
Hehe, life has a way of doing this 😛
