### ISSUE TITLE
Codemod breaks apps which use `layoutName` and partials

### ISSUE THREAD

**Issue by patocallaghan** [ember-codemods/ember-component-template-colocation-migrator#8]
So while both deprecated, if you do either of the following in your application and run this codemod it will break your app.

1. Set component templates using `layoutName`
```js
export default Component.extend({
  layoutName: 'components/attributes/attribute',
});
```
2. Use templates within `app/templates/components` as templates
```hbs
{{partial "components/modal/message"}}
```

Both these mechanisms rely on the templates still appearing within `app/templates/components`. Currently we completely delete the `app/templates/components` directory. Should we instead be more selective and only move those templates which aren't used in `layoutName` or `partial`?

While testing out co-location in our app I found it was annoying to have to manually copy (partial and `layoutName`) template files back to their original locations so the app would work properly. So I went ahead forked this codemod and implemented the behavior where partials and layoutName templates are not moved and left where they are. If you think it's useful, I could submit a PR here with my changes?

**Comment by patocallaghan** [comment]
For anyone coming here and having the same problem, I currently have this working in a branch in https://github.com/patocallaghan/ember-component-template-colocation-migrator/commit/ad762c4d39623a6e387ec30a49b956ccb9e24c15

You can run it by doing

```
npx github:patocallaghan/ember-component-template-colocation-migrator#patoc/keep-layout-name-templates
```

I'll submit a PR back once I clean it up and have time 😬

**Comment by rwjblue** [comment]
Awesome, thanks @patocallaghan!
